import XCTest

@testable import TypeReviewKit

/// The contract between this port and the TypeScript engine it came from.
///
/// Vectors are generated by `scripts/emit-golden-vectors.ts` in the web repo
/// and committed here. Comparisons are exact: both implementations run IEEE
/// doubles through the same operations in the same order, so "close enough"
/// would hide precisely the divergences these exist to catch.
final class GoldenVectorTests: XCTestCase {
    /// Loads a vector file from the test bundle.
    private func vector<T: Decodable>(_ name: String, as type: T.Type) throws -> T {
        guard let url = Bundle.module.url(forResource: "Vectors/\(name)", withExtension: "json")
        else {
            throw XCTSkip("Vectors/\(name).json is missing — regenerate with `pnpm emit:vectors`")
        }
        return try JSONDecoder().decode(T.self, from: Data(contentsOf: url))
    }

    // MARK: - RNG

    struct RNGCase: Decodable {
        let seed: UInt32
        let draws: [Double]
    }

    func testMulberry32MatchesTheTypeScriptStreamExactly() throws {
        let cases = try vector("rng", as: [RNGCase].self)
        XCTAssertFalse(cases.isEmpty)
        for testCase in cases {
            var rng = Mulberry32(seed: testCase.seed)
            for (index, expected) in testCase.draws.enumerated() {
                let actual = rng.next()
                XCTAssertEqual(
                    actual, expected,
                    "seed \(testCase.seed) draw \(index): got \(actual), expected \(expected)")
            }
        }
    }

    func testTheSignedTranspositionWouldHaveBeenCaught() throws {
        // Guards the guard. The whole reason these vectors exist is that the
        // Int32 port is plausible and wrong, so assert that the value it would
        // produce is NOT what we produce — otherwise a future refactor could
        // reintroduce it and the suite would stay green.
        let cases = try vector("rng", as: [RNGCase].self)
        guard let seed42 = cases.first(where: { $0.seed == 42 }) else {
            throw XCTSkip("no seed-42 vector")
        }
        let first = try XCTUnwrap(seed42.draws.first)
        XCTAssertEqual(first, 0.6011037519201636)
        XCTAssertNotEqual(first, 0.39889427926391363)
    }

    // MARK: - Math

    struct ScalarCase: Decodable {
        let input: Double
        let output: Double
    }

    struct ArrayCase: Decodable {
        let input: [Double]
        let output: Double
    }

    struct MathVectors: Decodable {
        let roundTo2: [ScalarCase]
        let mean: [ArrayCase]
        let stdDev: [ArrayCase]
        let kogasa: [ScalarCase]
    }

    func testRoundingBreaksTiesTheWayJavaScriptDoes() throws {
        let vectors = try vector("math", as: MathVectors.self)
        for testCase in vectors.roundTo2 {
            XCTAssertEqual(
                Stats.roundTo2(testCase.input), testCase.output,
                "roundTo2(\(testCase.input))")
        }
        // The asymmetry in one assertion, so the intent survives a vector
        // regeneration: +2.675 rounds up, −2.675 rounds *up* too, toward +∞.
        XCTAssertEqual(Stats.roundTo2(2.675), 2.68)
        XCTAssertEqual(Stats.roundTo2(-2.675), -2.67)
    }

    func testMeanAndStandardDeviationMatchToTheLastBit() throws {
        let vectors = try vector("math", as: MathVectors.self)
        for testCase in vectors.mean {
            XCTAssertEqual(Stats.mean(testCase.input), testCase.output, "mean(\(testCase.input))")
        }
        for testCase in vectors.stdDev {
            XCTAssertEqual(
                Stats.stdDev(testCase.input), testCase.output, "stdDev(\(testCase.input))")
        }
    }

    func testConsistencyCurveMatches() throws {
        let vectors = try vector("math", as: MathVectors.self)
        for testCase in vectors.kogasa {
            XCTAssertEqual(Stats.kogasa(testCase.input), testCase.output, "kogasa(\(testCase.input))")
        }
    }
}
